profile = "iterion-default"

[profiles.iterion-default]
approval_policy = "on-request"
model_reasoning_effort = "high"
sandbox_mode = "workspace-write"

[projects."/Users/iterion/Development"]
trust_level = "trusted"

[projects."/Users/iterion/dotfiles"]
trust_level = "trusted"

[sandbox_workspace_write]
network_access = true
writable_roots = [
  "/Users/iterion/.cache",
  "/Users/iterion/.cargo",
  "/Users/iterion/.cargo/registry/cache",
  "/Users/iterion/.cargo/git/db",
  "/Users/iterion/.npm",
  "/Users/iterion/.cache/node",
  "/Users/iterion/.cache/yarn",
  "/Users/iterion/Library/Application Support",
  "/Users/iterion/Library/Caches",
  "/Users/iterion/Library/Caches/Yarn",
  "/Users/iterion/Library/pnpm",
  "/tmp"
]

[tools]
web_search = true
