# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-094ec82f-8ddd-4d54-9b93-cc68961f2fa8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-094ec82f-8ddd-4d54-9b93-cc68961f2fa8".device = "/dev/disk/by-uuid/094ec82f-8ddd-4d54-9b93-cc68961f2fa8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DD19-69D9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b2aeb4e9-6fec-49f7-a40b-166fafdbf771"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
